// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BANDAAV1.Model
{
    [Table("TBalbum")]
    public partial class Tbalbum
    {
        public Tbalbum()
        {
            Tbmusica = new HashSet<Tbmusica>();
        }

        [Key]
        [Column("albumId")]
        [Display(Name = "Código")]
        public int AlbumId { get; set; }
        [Column("bandaId")]       
        public int BandaId { get; set; }
        [Required]
        [Column("albumNome")]
        [Display(Name = "Nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string AlbumNome { get; set; }

        [ForeignKey("BandaId")]
        [InverseProperty("Tbalbum")]
        public virtual Tbbanda Banda { get; set; }
        [InverseProperty("Album")]
        public virtual ICollection<Tbmusica> Tbmusica { get; set; }
    }
}