// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BANDAAV1.Model
{
    [Table("TBbanda")]
    public partial class Tbbanda
    {
        public Tbbanda()
        {
            Tbalbum = new HashSet<Tbalbum>();
        }

        [Key]
        [Column("bandaId")]
        [Display(Name ="Código")]
        public int BandaId { get; set; }
        [Required]
        [Column("bandaNome")]
        [Display(Name = "Nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string BandaNome { get; set; }
        [Required]
        [Column("bandagenero")]
        [Display(Name = "Gênero")]
        [StringLength(50)]
        [Unicode(false)]
        public string Bandagenero { get; set; }

        [InverseProperty("Banda")]
        public virtual ICollection<Tbalbum> Tbalbum { get; set; }
    }
}