// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BANDAAV1.Model
{
    [Table("TBmusica")]
    public partial class Tbmusica
    {
        [Key]
        [Column("musicaId")]
        public int MusicaId { get; set; }
        [Column("albumId")]
        public int AlbumId { get; set; }
        [Required]
        [Column("musicaNome")]
        [StringLength(50)]
        [Unicode(false)]
        public string MusicaNome { get; set; }

        [ForeignKey("AlbumId")]
        [InverseProperty("Tbmusica")]
        public virtual Tbalbum Album { get; set; }
    }
}